// Generated by https://quicktype.io

export interface PokeApiTypeResponse {
  damage_relations: DamageRelations
  game_indices: GameIndex[]
  generation: NamedAPIResource
  id: number
  move_damage_class: NamedAPIResource
  moves: NamedAPIResource[]
  name: string
  names: Name[]
  past_damage_relations: PastDamageRelation[]
  pokemon: Pokemon[]
}

export interface DamageRelations {
  double_damage_from: NamedAPIResource[]
  double_damage_to: NamedAPIResource[]
  half_damage_from: NamedAPIResource[]
  half_damage_to: NamedAPIResource[]
  no_damage_from: NamedAPIResource[]
  no_damage_to: NamedAPIResource[]
}

export interface NamedAPIResource {
  name: string
  url: string
}

export interface GameIndex {
  game_index: number
  generation: NamedAPIResource
}

export interface Name {
  language: NamedAPIResource
  name: string
}

export interface PastDamageRelation {
  damage_relations: DamageRelations
  generation: NamedAPIResource
}

export interface Pokemon {
  pokemon: NamedAPIResource
  slot: number
}
