export enum SelectedStatus {
  BASE = 'BASE',
  MIN = 'MIN',
  MAX = 'MAX',
}

export const formColors = {
  'charizard-mega-x': 'black',
  'latias-mega': 'purple',
  'latios-mega': 'purple',
  'castform-sunny': 'red',
  'castform-rainy': 'blue',
  'castform-snowy': 'purple',
  'burmy-sandy': 'brown',
  'burmy-trash': 'pink',
  'rotom-heat': 'red',
  'rotom-wash': 'blue',
  'rotom-frost': 'purple',
  'rotom-fan': 'yellow',
  'rotom-mow': 'green',
  'wormadam-sandy': 'brown',
  'wormadam-trash': 'pink',
  'darmanitan-zen': 'gray',
  'kyurem-black': 'black',
  'kyurem-white': 'white',
  'oricorio-pom-pom': 'yellow',
  'oricorio-pau': 'pink',
  'oricorio-sensu': 'purple',
  'lycanroc-midnight': 'red',
  'lycanroc-dusk': 'brown',
  'minior-orange-meteor': 'red', // Because its second in "pokemon.varieties"; actually its minior-red
  'necrozma-ultra': 'yellow',
  'magearna-original': 'red',
  'rattata-alola': 'black',
  'raticate-alola': 'black',
  'raichu-alola': 'brown',
  'sandshrew-alola': 'blue',
  'sandslash-alola': 'blue',
  'vulpix-alola': 'white',
  'ninetales-alola': 'white',
  'meowth-alola': 'gray',
  'persian-alola': 'gray',
  'grimer-alola': 'green',
  'muk-alola': 'green',
  'marowak-alola': 'black',
  'meowth-galar': 'brown',
  'ponyta-galar': 'pink',
  'rapidash-galar': 'pink',
  'mr-mime-galar': 'blue',
  'corsola-galar': 'white',
  'zigzagoon-galar': 'black',
  'linoone-galar': 'black',
  'darumaka-galar': 'white',
  'darmanitan-galar-standard': 'white',
  'darmanitan-galar-zen': 'white',
  'stunfisk-galar': 'gray',
  'articuno-galar': 'purple',
  'zapdos-galar': 'red',
  'moltres-galar': 'black',
  'slowking-galar': 'purple',
  'growlithe-hisui': 'red',
  'arcanine-hisui': 'gray',
  'voltorb-hisui': 'red',
  'electrode-hisui': 'red',
  'qwilfish-hisui': 'black',
  'sneasel-hisui': 'purple',
  'zorua-hisui': 'white',
  'zoroark-hisui': 'white',
  'braviary-hisui': 'white',
  'calyrex-ice': 'white',
  'calyrex-shadow': 'purple',
}
